name: Build and Release SillyPasswords

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install Python dependencies
      run: pip install PyQt6 pyinstaller

    - name: Download and Install UPX
      run: |
        curl -LO https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip
        unzip upx-4.2.1-win64.zip
        mv upx-4.2.1-win64 upx
        mv upx Extra/
      shell: bash

    - name: Build SillyPasswords
      run: pyinstaller --noconfirm --onedir --windowed --icon "Assets/Raubtier.ico" --name "SillyPasswords" --upx-dir "Extra/upx" --clean --version-file "Extra/fileversion.txt" --add-data "Src/about.py;." --add-data "Src/constants.py;." --add-data "Src/gui.py;." --add-data "Src/password_generator.py;." --add-data "Src/themes.py;." --add-data "Assets;Assets/"  "Src/main.py"

    - name: Remove Raubtier
      run: rm dist/SillyPasswords/_internal/Assets/Raubtier.gif
      shell: bash

    - name: Move Assets folder
      run: |
        mkdir -p dist/SillyPasswords
        mv dist/SillyPasswords/_internal/Assets dist/SillyPasswords/
      shell: bash

    - name: Archive SillyPasswords
      run: |
        tar --create --xz --verbose --options=lzma,lc=1,lp=0,pb=0 --file=dist/SillyPasswords-1.x.x-x64-win.tar.xz -C dist SillyPasswords
      shell: bash

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SillyPasswords-1.x.x-x64-win.tar.xz
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
