name: Build and Release SillyPasswords

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install Python dependencies
      run: pip install PyQt6 pyinstaller

    - name: Download and Install UPX
      run: |
        curl -LO https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip
        unzip upx-4.2.1-win64.zip
        mv upx-4.2.1-win64 upx
        mv upx Extra/
      shell: bash

    - name: Build SillyPasswords
      run: pyinstaller --noconfirm --onedir --windowed --icon "Assets/Raubtier.ico" --name "SillyPasswords" --upx-dir "Extra/upx" --clean --version-file "Extra/fileversion.txt" --add-data "Src/about.py;." --add-data "Src/constants.py;." --add-data "Src/gui.py;." --add-data "Src/password_generator.py;." --add-data "Src/themes.py;." --add-data "Assets;Assets/"  "Src/main.py"

    - name: Remove Raubtier
      run: rm dist/SillyPasswords/_internal/Assets/Raubtier.gif
      shell: bash

    - name: Move Assets folder
      run: |
        mkdir -p dist/SillyPasswords
        mv dist/SillyPasswords/_internal/Assets dist/SillyPasswords/
      shell: bash

    - name: Upload SillyPasswords
      uses: actions/upload-artifact@v3.1.3
      with:
        name: SillyPasswords
        path: dist/SillyPasswords
